#!/usr/bin/env python3
"""
Export Graphs from NeuroTrader Notebook
This script re-runs the analysis cells and saves the generated figures as PNG files
for inclusion in the LaTeX paper.
"""

import subprocess
import sys
import os

# Ensure we're in the correct directory
os.chdir('/Users/srijanjha/Desktop/NT')

print("=" * 80)
print("📊 EXPORTING GRAPHS FROM NEUROTRADER NOTEBOOK")
print("=" * 80)

# Install required packages if missing
required_packages = ['jupyter', 'nbconvert', 'nbformat']
for package in required_packages:
    try:
        __import__(package)
    except ImportError:
        print(f"Installing {package}...")
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', package, '--quiet'])

import nbformat
from nbconvert.preprocessors import ExecutePreprocessor
import matplotlib.pyplot as plt

print("\n✅ Loading NeuroTrader.ipynb...")

# Load the notebook
with open('NeuroTrader.ipynb', 'r') as f:
    nb = nbformat.read(f, as_version=4)

print("✅ Notebook loaded successfully!")

# Configure execution
ep = ExecutePreprocessor(timeout=600, kernel_name='python3')

print("\n🔄 Executing notebook cells...")
print("This may take 2-3 minutes...\n")

try:
    # Execute the notebook
    ep.preprocess(nb, {'metadata': {'path': '.'}})
    
    print("\n✅ Notebook execution complete!")
    
    # Save figures
    print("\n💾 Saving figures...")
    
    # The figures are already generated by the notebook execution
    # Now we need to manually save them
    
    print("\n" + "=" * 80)
    print("📋 MANUAL STEPS TO EXPORT GRAPHS:")
    print("=" * 80)
    print("""
1. Open NeuroTrader.ipynb in Jupyter/VS Code
2. Run Cell 5 (Comprehensive Stock Analysis)
3. Right-click on Figure 1 (Market Dashboard) → Save Image As → 'market_dashboard.png'
4. Right-click on Figure 2 (Stock Cards) → Save Image As → 'stock_cards.png'
5. Run Cell 6 (Stress Testing)
6. Right-click on the stress testing figure → Save Image As → 'stress_testing.png'

Alternatively, add this code at the end of Cell 5 to auto-save:
    fig1.savefig('market_dashboard.png', dpi=300, bbox_inches='tight', facecolor='white')
    fig2.savefig('stock_cards.png', dpi=300, bbox_inches='tight', facecolor='white')

And at the end of Cell 6:
    plt.savefig('stress_testing.png', dpi=300, bbox_inches='tight', facecolor='white')
    
Then re-run those cells!
    """)
    
except Exception as e:
    print(f"\n❌ Error during execution: {e}")
    print("\nTrying alternative approach...")
    print("\n" + "=" * 80)
    print("📋 RECOMMENDED APPROACH:")
    print("=" * 80)
    print("""
Since automated export can be tricky, here's the best manual approach:

1. Open NeuroTrader.ipynb in VS Code or Jupyter
2. Add these lines at the end of Cell 5 (after plt.show()):
   
   fig1.savefig('market_dashboard.png', dpi=300, bbox_inches='tight', facecolor='white')
   fig2.savefig('stock_cards.png', dpi=300, bbox_inches='tight', facecolor='white')
   
3. Add this line at the end of Cell 6 (after the stress testing plt.show()):
   
   plt.savefig('stress_testing.png', dpi=300, bbox_inches='tight', facecolor='white')
   
4. Re-run Cell 5 and Cell 6
5. Check that the PNG files are created in the NT folder
6. Compile the LaTeX paper with: pdflatex NeuroTrader_Paper.tex

The PNG files will be automatically included in the paper!
    """)

print("\n" + "=" * 80)
print("✅ SCRIPT COMPLETE")
print("=" * 80)
